version: '3'

env:
  ENV: development

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks: 
  lint: 
    cmds: 
      - golangci-lint run ./...
  detect-version:
    cmds:
      - export GIT_TAG="${git describe --tags --abbrev=0}"
  release:
    goreleaser release
